"""add column talk

Revision ID: 032862d300b1
Revises: cf840803ab9f
Create Date: 2024-09-22 15:14:19.627794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032862d300b1'
down_revision: Union[str, None] = 'cf840803ab9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('talk', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'talk')
    # ### end Alembic commands ###
