"""Initial migration

Revision ID: 3bfb0334ce93
Revises: 
Create Date: 2024-08-22 08:53:56.905927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bfb0334ce93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chairs', 'invitation_status')
    op.drop_column('chairs', 'invitation_expiration_date')
    op.drop_column('organizers', 'invitation_status')
    op.drop_column('organizers', 'invitation_expiration_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizers', sa.Column('invitation_expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('organizers', sa.Column('invitation_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('chairs', sa.Column('invitation_expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('chairs', sa.Column('invitation_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
