"""Modify events with review column

Revision ID: 3e10c5addd42
Revises: 78f1fbc0f9f4
Create Date: 2024-06-19 12:27:05.549758

"""
from typing import Sequence, Union
from app.database.models.organizer import InvitationStatus
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = '3e10c5addd42'
down_revision: Union[str, None] = '78f1fbc0f9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('review_skeleton', sa.JSON(), nullable=True))
    op.add_column('organizers', sa.Column('invitation_expiration_date', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('organizers', sa.Column('invitation_status', sa.String(), nullable=True, server_default=InvitationStatus.ACCEPTED.value))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizers', 'invitation_status')
    op.drop_column('organizers', 'invitation_expiration_date')
    op.drop_column('events', 'review_skeleton')
    # ### end Alembic commands ###
