"""submissions model update

Revision ID: 985d78f44fbb
Revises: c3b4a8ec0324
Create Date: 2024-08-13 20:32:03.673977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '985d78f44fbb'
down_revision: Union[str, None] = 'c3b4a8ec0324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chairs', sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('events', sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('inscriptions', sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('organizers', sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('submissions', sa.Column('creation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('submissions', sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('submissions', 'public_review')
    op.drop_column('submissions', 'review_comments')
    op.drop_column('submissions', 'review_decision')
    op.add_column('users', sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('works', sa.Column('creation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('works', sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'last_update')
    op.drop_column('works', 'creation_date')
    op.drop_column('users', 'last_update')
    op.add_column('submissions', sa.Column('review_decision', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('review_comments', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('public_review', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('submissions', 'last_update')
    op.drop_column('submissions', 'creation_date')
    op.drop_column('organizers', 'last_update')
    op.drop_column('inscriptions', 'last_update')
    op.drop_column('events', 'last_update')
    op.drop_column('chairs', 'last_update')
    # ### end Alembic commands ###
