"""Add dates and pricing to database

Revision ID: a85757302459
Revises: dafacd72ff1e
Create Date: 2024-07-22 21:08:53.386517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a85757302459'
down_revision: Union[str, None] = 'dafacd72ff1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('notification_mails', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('events', sa.Column('contact', sa.String(), nullable=True))
    op.add_column('events', sa.Column('organized_by', sa.String(), nullable=True))
    op.add_column('events', sa.Column('media', sa.ARRAY(sa.JSON()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'media')
    op.drop_column('events', 'organized_by')
    op.drop_column('events', 'contact')
    op.drop_column('events', 'notification_mails')
    # ### end Alembic commands ###
