"""add prices database

Revision ID: dafacd72ff1e
Revises: 3e10c5addd42
Create Date: 2024-07-18 19:20:53.556932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dafacd72ff1e'
down_revision: Union[str, None] = '3e10c5addd42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('pricing', sa.JSON(), nullable=True))
    op.add_column('events', sa.Column('dates', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'dates')
    op.drop_column('events', 'pricing')
    # ### end Alembic commands ###
