"""change dates format in db

Revision ID: ef28569649cf
Revises: f421bf985d59
Create Date: 2024-07-27 19:46:36.580538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef28569649cf'
down_revision: Union[str, None] = 'f421bf985d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'end_date')
    op.drop_column('events', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
