"""update datebase models

Revision ID: f9a7e3c00b42
Revises: 3682fd855be9
Create Date: 2024-07-29 01:48:01.232027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9a7e3c00b42'
down_revision: Union[str, None] = '3682fd855be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text('DELETE FROM organizers'))
    op.execute(sa.text('DELETE FROM reviews'))
    op.execute(sa.text('DELETE FROM events'))

    op.add_column('reviews', sa.Column('review_status', sa.Enum('ACCEPTED', 'REJECTED', 'RE_SUBMIT', 'PENDING', name='reviewstatus'), nullable=False))
    op.add_column('submissions', sa.Column('public_review', sa.Boolean(), nullable=False))
    op.add_column('works', sa.Column('state', sa.Enum('ACCEPTED', 'REJECTED', 'RE_SUBMIT', 'IN_REVISION', 'SUBMITTED', name='workstates'), nullable=False))
    op.alter_column('works', 'deadline_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint('works_reviewer_id_fkey', 'works', type_='foreignkey')
    op.drop_column('works', 'reviewer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('reviewer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('works_reviewer_id_fkey', 'works', 'users', ['reviewer_id'], ['id'])
    op.alter_column('works', 'deadline_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('works', 'state')
    op.drop_column('submissions', 'public_review')
    op.drop_column('reviews', 'review_status')
    # ### end Alembic commands ###
